### ISSUE TITLE
Feature request: add buttons for places

### ISSUE THREAD

**Issue by ojlaw** [WazeDev/WME-URComments-Enhanced#38]
it would be awesome if buttons could be added similar to the road button that adds street name for-
Place name- the name of any point or area place
RPP address- include the HN, Street, City, State for an RPP

also if the feature could be used in the $xxx$ format for standard replies, perhaps $PLACENAME$ and $ADDRESS$ 

thank you for your consideration.

**Comment by dBsooner** [comment]
Added to latest version of beta. Usage is $PLACE_NAME$ and $PLACE_ADDRESS$. They are also available as shortcut buttons as requested.
