### ISSUE TITLE
Feature Request: allow custom tags on Except tags in Auto send reminders 

### ISSUE THREAD

**Issue by ojlaw** [WazeDev/WME-URComments-Enhanced#56]
Currently when Except tagged is checked on Auto send reminders URC-E will send reminders on tags like [OJ] and []. It would be nice if it would not Auto send reminders on custom tags, basically anything inside []. This would be useful for initial comments where the editor says something along the lines of "We made some adjustments here. We will check back in a few days after the system updates. Thanks! [OJ]." Some initial comments require more feedback from the editor before feedback from the reporter and the current implementation of Auto send reminders does not allow for this. Thank you for your consideration.

**Comment by dBsooner** [comment]
Done. if [] exists anywhere in any of the comments or report, it will not send autoreminders. THe [] can even exist in different comments. Example:
Comment 1: [I FORGOT TO CLOSE MY ...
COmment 2: Bracket. ]

That would trigger it to not send reminder.
