### ISSUE TITLE
Selected comment list resets to default on reload/new tab

### ISSUE THREAD

**Issue by StormeHawke** [WazeDev/WME-URComments-Enhanced#73]
I'm seeing an issue where the comment list is consistently resetting to the default "CommentTeam" list on reload or new editor tab.

Running the latest firefox on MacOS Monterey:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/540587/190653950-03dfece0-2699-48e6-a4d1-81b54b893a0b.png">

I turned off all other scripts and it still happens. I do see this in the logs when selecting a comment list, not sure if it's related but it happens every time:

![image](https://user-images.githubusercontent.com/540587/190654369-93aa5fb9-8d51-4e14-915d-0f4f335cc7ba.png)

My waze username is phoenixhawke, feel free to ping me on Discord if you need help debugging.

**Comment by dBsooner** [comment]
This should have been resolved a long time ago.
